dishes:
    type: rest
    resource: "routing/dishes.yml"

images:
    type: rest
    resource: "@AppBundle/Controller/ImagesController.php"

users:
    type: rest
    resource: "@AppBundle/Controller/UsersController.php"
